# Generated by Django 4.2.1 on 2023-06-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number_of_likes',
        ),
    ]
