# Generated by Django 4.2.1 on 2023-06-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='number_of_likes',
            new_name='likes_number',
        ),
    ]
